/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Usuario;

/**
 *
 * @author sarai
 */
public class Saludo extends javax.swing.JFrame {

    /**
     * Creates new form Saludo
     */
    public Saludo() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtauto = new javax.swing.JButton();
        txtmoto = new javax.swing.JButton();
        txtautobus = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setBackground(new java.awt.Color(153, 0, 204));
        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 255));
        jLabel1.setText("   Tipo de Vehiculo");

        txtauto.setBackground(new java.awt.Color(102, 204, 255));
        txtauto.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtauto.setForeground(new java.awt.Color(51, 0, 51));
        txtauto.setText("Auto");
        txtauto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtautoMouseClicked(evt);
            }
        });
        txtauto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtautoActionPerformed(evt);
            }
        });

        txtmoto.setBackground(new java.awt.Color(51, 153, 255));
        txtmoto.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtmoto.setForeground(new java.awt.Color(51, 0, 51));
        txtmoto.setText("Moto");
        txtmoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtmotoActionPerformed(evt);
            }
        });

        txtautobus.setBackground(new java.awt.Color(102, 153, 255));
        txtautobus.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtautobus.setForeground(new java.awt.Color(51, 0, 51));
        txtautobus.setText("Camion");
        txtautobus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtautobusActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addComponent(txtautobus))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(146, 146, 146)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtmoto)
                            .addComponent(txtauto)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(91, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(txtauto)
                .addGap(18, 18, 18)
                .addComponent(txtmoto)
                .addGap(29, 29, 29)
                .addComponent(txtautobus)
                .addContainerGap(90, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtautoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtautoMouseClicked
    // TODO add your handling code here:
    }//GEN-LAST:event_txtautoMouseClicked

    private void txtautoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtautoActionPerformed
       Auto ven = new Auto();
       ven.setVisible(true);
       this.setVisible(false);
    }//GEN-LAST:event_txtautoActionPerformed

    private void txtmotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtmotoActionPerformed
       Moto ven = new Moto();
       ven.setVisible(true);
       this.setVisible(false);
    }//GEN-LAST:event_txtmotoActionPerformed

    private void txtautobusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtautobusActionPerformed
       Ejes ven = new Ejes();
       ven.setVisible(true);
       this.setVisible(false);
    }//GEN-LAST:event_txtautobusActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Saludo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Saludo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Saludo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Saludo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Saludo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton txtauto;
    private javax.swing.JButton txtautobus;
    private javax.swing.JButton txtmoto;
    // End of variables declaration//GEN-END:variables
}
